kafka:
  bootstrap-servers: localhost:9092
  application-id: kafka-demo
  auto-offset-reset-config: earliest
  acks: 1
  retries: 3
  schema-registry-url: http://localhost:8081

  customer-input-topic: customer
  purchase-input-topic: mysql.demo.purchase
  detail-output-topic: purchase-detail

  logging:
    level:
      root: warn