/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.godeltech.com.kafkademo.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PurchaseDetail extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8530558063212878214L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PurchaseDetail\",\"namespace\":\"com.godeltech.com.kafkademo.schema\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"first_name\",\"type\":\"string\"},{\"name\":\"second_name\",\"type\":\"string\"},{\"name\":\"product\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"price\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"occurred_at\",\"type\":[\"null\",{\"type\":\"string\",\"connect.name\":\"io.debezium.time.ZonedTimestamp\",\"connect.version\":1}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PurchaseDetail> ENCODER =
      new BinaryMessageEncoder<PurchaseDetail>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PurchaseDetail> DECODER =
      new BinaryMessageDecoder<PurchaseDetail>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<PurchaseDetail> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<PurchaseDetail> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PurchaseDetail>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this PurchaseDetail to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a PurchaseDetail from a ByteBuffer. */
  public static PurchaseDetail fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long id;
  @Deprecated public java.lang.CharSequence first_name;
  @Deprecated public java.lang.CharSequence second_name;
  @Deprecated public java.lang.CharSequence product;
  @Deprecated public java.lang.Double price;
  @Deprecated public java.lang.CharSequence occurred_at;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PurchaseDetail() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param first_name The new value for first_name
   * @param second_name The new value for second_name
   * @param product The new value for product
   * @param price The new value for price
   * @param occurred_at The new value for occurred_at
   */
  public PurchaseDetail(java.lang.Long id, java.lang.CharSequence first_name, java.lang.CharSequence second_name, java.lang.CharSequence product, java.lang.Double price, java.lang.CharSequence occurred_at) {
    this.id = id;
    this.first_name = first_name;
    this.second_name = second_name;
    this.product = product;
    this.price = price;
    this.occurred_at = occurred_at;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return first_name;
    case 2: return second_name;
    case 3: return product;
    case 4: return price;
    case 5: return occurred_at;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: first_name = (java.lang.CharSequence)value$; break;
    case 2: second_name = (java.lang.CharSequence)value$; break;
    case 3: product = (java.lang.CharSequence)value$; break;
    case 4: price = (java.lang.Double)value$; break;
    case 5: occurred_at = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'first_name' field.
   * @return The value of the 'first_name' field.
   */
  public java.lang.CharSequence getFirstName() {
    return first_name;
  }

  /**
   * Sets the value of the 'first_name' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.first_name = value;
  }

  /**
   * Gets the value of the 'second_name' field.
   * @return The value of the 'second_name' field.
   */
  public java.lang.CharSequence getSecondName() {
    return second_name;
  }

  /**
   * Sets the value of the 'second_name' field.
   * @param value the value to set.
   */
  public void setSecondName(java.lang.CharSequence value) {
    this.second_name = value;
  }

  /**
   * Gets the value of the 'product' field.
   * @return The value of the 'product' field.
   */
  public java.lang.CharSequence getProduct() {
    return product;
  }

  /**
   * Sets the value of the 'product' field.
   * @param value the value to set.
   */
  public void setProduct(java.lang.CharSequence value) {
    this.product = value;
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public java.lang.Double getPrice() {
    return price;
  }

  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(java.lang.Double value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'occurred_at' field.
   * @return The value of the 'occurred_at' field.
   */
  public java.lang.CharSequence getOccurredAt() {
    return occurred_at;
  }

  /**
   * Sets the value of the 'occurred_at' field.
   * @param value the value to set.
   */
  public void setOccurredAt(java.lang.CharSequence value) {
    this.occurred_at = value;
  }

  /**
   * Creates a new PurchaseDetail RecordBuilder.
   * @return A new PurchaseDetail RecordBuilder
   */
  public static com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder newBuilder() {
    return new com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder();
  }

  /**
   * Creates a new PurchaseDetail RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PurchaseDetail RecordBuilder
   */
  public static com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder newBuilder(com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder other) {
    return new com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder(other);
  }

  /**
   * Creates a new PurchaseDetail RecordBuilder by copying an existing PurchaseDetail instance.
   * @param other The existing instance to copy.
   * @return A new PurchaseDetail RecordBuilder
   */
  public static com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder newBuilder(com.godeltech.com.kafkademo.schema.PurchaseDetail other) {
    return new com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder(other);
  }

  /**
   * RecordBuilder for PurchaseDetail instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PurchaseDetail>
    implements org.apache.avro.data.RecordBuilder<PurchaseDetail> {

    private long id;
    private java.lang.CharSequence first_name;
    private java.lang.CharSequence second_name;
    private java.lang.CharSequence product;
    private java.lang.Double price;
    private java.lang.CharSequence occurred_at;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.first_name)) {
        this.first_name = data().deepCopy(fields()[1].schema(), other.first_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.second_name)) {
        this.second_name = data().deepCopy(fields()[2].schema(), other.second_name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.product)) {
        this.product = data().deepCopy(fields()[3].schema(), other.product);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.price)) {
        this.price = data().deepCopy(fields()[4].schema(), other.price);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.occurred_at)) {
        this.occurred_at = data().deepCopy(fields()[5].schema(), other.occurred_at);
        fieldSetFlags()[5] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PurchaseDetail instance
     * @param other The existing instance to copy.
     */
    private Builder(com.godeltech.com.kafkademo.schema.PurchaseDetail other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.first_name)) {
        this.first_name = data().deepCopy(fields()[1].schema(), other.first_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.second_name)) {
        this.second_name = data().deepCopy(fields()[2].schema(), other.second_name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.product)) {
        this.product = data().deepCopy(fields()[3].schema(), other.product);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.price)) {
        this.price = data().deepCopy(fields()[4].schema(), other.price);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.occurred_at)) {
        this.occurred_at = data().deepCopy(fields()[5].schema(), other.occurred_at);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'first_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirstName() {
      return first_name;
    }

    /**
      * Sets the value of the 'first_name' field.
      * @param value The value of 'first_name'.
      * @return This builder.
      */
    public com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.first_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'first_name' field has been set.
      * @return True if the 'first_name' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'first_name' field.
      * @return This builder.
      */
    public com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder clearFirstName() {
      first_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'second_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getSecondName() {
      return second_name;
    }

    /**
      * Sets the value of the 'second_name' field.
      * @param value The value of 'second_name'.
      * @return This builder.
      */
    public com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder setSecondName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.second_name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'second_name' field has been set.
      * @return True if the 'second_name' field has been set, false otherwise.
      */
    public boolean hasSecondName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'second_name' field.
      * @return This builder.
      */
    public com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder clearSecondName() {
      second_name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'product' field.
      * @return The value.
      */
    public java.lang.CharSequence getProduct() {
      return product;
    }

    /**
      * Sets the value of the 'product' field.
      * @param value The value of 'product'.
      * @return This builder.
      */
    public com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder setProduct(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.product = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'product' field has been set.
      * @return True if the 'product' field has been set, false otherwise.
      */
    public boolean hasProduct() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'product' field.
      * @return This builder.
      */
    public com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder clearProduct() {
      product = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public java.lang.Double getPrice() {
      return price;
    }

    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder setPrice(java.lang.Double value) {
      validate(fields()[4], value);
      this.price = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder clearPrice() {
      price = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'occurred_at' field.
      * @return The value.
      */
    public java.lang.CharSequence getOccurredAt() {
      return occurred_at;
    }

    /**
      * Sets the value of the 'occurred_at' field.
      * @param value The value of 'occurred_at'.
      * @return This builder.
      */
    public com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder setOccurredAt(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.occurred_at = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'occurred_at' field has been set.
      * @return True if the 'occurred_at' field has been set, false otherwise.
      */
    public boolean hasOccurredAt() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'occurred_at' field.
      * @return This builder.
      */
    public com.godeltech.com.kafkademo.schema.PurchaseDetail.Builder clearOccurredAt() {
      occurred_at = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PurchaseDetail build() {
      try {
        PurchaseDetail record = new PurchaseDetail();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.first_name = fieldSetFlags()[1] ? this.first_name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.second_name = fieldSetFlags()[2] ? this.second_name : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.product = fieldSetFlags()[3] ? this.product : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.price = fieldSetFlags()[4] ? this.price : (java.lang.Double) defaultValue(fields()[4]);
        record.occurred_at = fieldSetFlags()[5] ? this.occurred_at : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PurchaseDetail>
    WRITER$ = (org.apache.avro.io.DatumWriter<PurchaseDetail>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PurchaseDetail>
    READER$ = (org.apache.avro.io.DatumReader<PurchaseDetail>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
